package ru.coutvv.puzzle.character;

/**
 * why   ? Unicode последовательность в \\units(в оригинале там один бэкслэш) мешает скомпилиться ибо нет такого хекса
 * fix	 ? не использовать unicode последовательности в комментах?   
 *
 * moral : 
 * 			- используй HTML-последовательности в JavaDoc комментах
 *   
 * @author coutvv
 */

/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0 
 * from F:\TestRoot\apps\a1\\units\include\PolicyHome.idl
 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */
public class HelloWhirled {

	public static void main(String[] args) {
		System.out.print("Hell");
		System.out.println("o world");
	}
}
